/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Criatividade;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author heylor
 */
public class Criatividade extends javax.swing.JFrame {
    public void verifica(){
        switch(cboFundo.getSelectedIndex()){
        
            case 0:
                PanelFundo.setBackground(Color. WHITE);
                lblPeso.setForeground(Color.BLACK);
                lblAltura.setForeground(Color.BLACK);
                lblTitulo.setBackground(Color.CYAN);
                lblTitulo.setForeground(Color.BLACK);
                lblLanche.setForeground(Color.black);
                rbtPodrao.setForeground(Color.black);
                rbtSaudavel.setForeground(Color.black);
                lblDecisao.setForeground(Color.black);
                jLabel1.setForeground(Color.BLACK);
            break;
            
            case 1:
                PanelFundo.setBackground(Color. BLUE);
                lblPeso.setForeground(Color.YELLOW);
                lblAltura.setForeground(Color.YELLOW);
                lblTitulo.setBackground(Color.BLACK);
                lblTitulo.setForeground(Color.YELLOW);
                lblLanche.setForeground(Color.YELLOW);
                rbtPodrao.setForeground(Color.YELLOW);
                rbtSaudavel.setForeground(Color.YELLOW);
                lblDecisao.setForeground(Color.YELLOW);
                jLabel1.setForeground(Color.YELLOW);
            break;
            
            case 2:
                PanelFundo.setBackground(Color. BLACK);
                lblPeso.setForeground(Color.WHITE);
                lblAltura.setForeground(Color.WHITE);
                lblTitulo.setBackground(Color.WHITE);
                lblTitulo.setForeground(Color.WHITE);
                lblLanche.setForeground(Color.WHITE);
                rbtPodrao.setForeground(Color.WHITE);
                rbtSaudavel.setForeground(Color.WHITE);
                lblDecisao.setForeground(Color.WHITE);
                jLabel1.setForeground(Color.WHITE);
                
            break;
            
            case 3:
                PanelFundo.setBackground(Color. YELLOW);
                lblPeso.setForeground(Color.BLACK);
                lblAltura.setForeground(Color.BLACK);
                lblTitulo.setBackground(Color.RED);
                lblTitulo.setForeground(Color.BLACK);
                lblLanche.setForeground(Color.black);
                rbtPodrao.setForeground(Color.black);
                rbtSaudavel.setForeground(Color.black);
                lblDecisao.setForeground(Color.black);
                jLabel1.setForeground(Color.BLACK);
            break;
            case 4:
                PanelFundo.setBackground(Color. RED);
                lblPeso.setForeground(Color.YELLOW);
                lblAltura.setForeground(Color.YELLOW);
                lblTitulo.setBackground(Color.YELLOW);
                lblTitulo.setForeground(Color.YELLOW);
                lblLanche.setForeground(Color.YELLOW);
                rbtPodrao.setForeground(Color.YELLOW);
                rbtSaudavel.setForeground(Color.YELLOW);
                lblDecisao.setForeground(Color.YELLOW);
                jLabel1.setForeground(Color.YELLOW);
            break;
        
        }
    }
    
    float peso = 0.0f,altura = 0.0f, imc = 0.0f;

    /**
     * Creates new form Criatividade
     */
    public Criatividade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgComidas = new javax.swing.ButtonGroup();
        PanelFundo = new javax.swing.JPanel();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lblAltura = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        btnCalcularIMC = new javax.swing.JButton();
        lblIMC = new javax.swing.JLabel();
        cboFundo = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rbtPodrao = new javax.swing.JRadioButton();
        rbtSaudavel = new javax.swing.JRadioButton();
        lblLanche = new javax.swing.JLabel();
        btnPedirLanche = new javax.swing.JButton();
        lblDecisao = new javax.swing.JLabel();
        lblGordoOuMagro = new javax.swing.JLabel();
        lblSituation = new javax.swing.JLabel();
        btnEvitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SUPER HIPER IMC CALCULATOR");

        lblPeso.setFont(new java.awt.Font("GodOfWar", 0, 36)); // NOI18N
        lblPeso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPeso.setText("Digite seu peso: ");

        txtPeso.setFont(new java.awt.Font("Adeline", 3, 36)); // NOI18N
        txtPeso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblAltura.setFont(new java.awt.Font("GodOfWar", 0, 36)); // NOI18N
        lblAltura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAltura.setText("Digite sua altura:");

        txtAltura.setFont(new java.awt.Font("Adeline", 3, 36)); // NOI18N
        txtAltura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnCalcularIMC.setFont(new java.awt.Font("GodOfWar", 0, 18)); // NOI18N
        btnCalcularIMC.setText("Calcular IMC");
        btnCalcularIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularIMCActionPerformed(evt);
            }
        });

        lblIMC.setFont(new java.awt.Font("Adeline", 3, 36)); // NOI18N

        cboFundo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Branco", "Azul", "Preto", "Amarelo", "Vermelho" }));
        cboFundo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboFundoItemStateChanged(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("The Bold Font", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("THE MASTER CALCULADORA DE IMC QUE MUDA O FUNDO DE COR!!!!!!!!!");

        jLabel1.setText("Cor de Fundo: ");

        btgComidas.add(rbtPodrao);
        rbtPodrao.setFont(new java.awt.Font("Birds of Paradise  Personal use", 1, 24)); // NOI18N
        rbtPodrao.setText("Podrão do bairro");
        rbtPodrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPodraoActionPerformed(evt);
            }
        });

        btgComidas.add(rbtSaudavel);
        rbtSaudavel.setFont(new java.awt.Font("Birds of Paradise  Personal use", 1, 24)); // NOI18N
        rbtSaudavel.setText("Lanche Saudável");

        lblLanche.setFont(new java.awt.Font("GodOfWar", 1, 24)); // NOI18N
        lblLanche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLanche.setText("Que lanche vc quer?");

        btnPedirLanche.setFont(new java.awt.Font("GodOfWar", 0, 18)); // NOI18N
        btnPedirLanche.setText("Pedir Lanche");
        btnPedirLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirLancheActionPerformed(evt);
            }
        });

        lblDecisao.setFont(new java.awt.Font("Square721 Cn BT", 2, 24)); // NOI18N

        lblGordoOuMagro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Criatividade/interroga.jpg"))); // NOI18N

        lblSituation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSituation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSituation.setText("Sua situação corporal:");

        btnEvitar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEvitar.setText("Evitar Decepções");
        btnEvitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFundoLayout = new javax.swing.GroupLayout(PanelFundo);
        PanelFundo.setLayout(PanelFundoLayout);
        PanelFundoLayout.setHorizontalGroup(
            PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPeso)
                    .addComponent(txtAltura)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                    .addComponent(lblAltura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPeso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelFundoLayout.createSequentialGroup()
                        .addComponent(lblLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cboFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelFundoLayout.createSequentialGroup()
                        .addGroup(PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelFundoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelFundoLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnPedirLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDecisao, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalcularIMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFundoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSituation, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGordoOuMagro, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanelFundoLayout.createSequentialGroup()
                        .addGroup(PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelFundoLayout.createSequentialGroup()
                                .addComponent(rbtPodrao)
                                .addGap(18, 18, 18)
                                .addComponent(rbtSaudavel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEvitar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelFundoLayout.setVerticalGroup(
            PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalcularIMC, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelFundoLayout.createSequentialGroup()
                        .addGroup(PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtPodrao)
                            .addComponent(rbtSaudavel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPedirLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(lblDecisao, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFundoLayout.createSequentialGroup()
                        .addComponent(lblSituation, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGordoOuMagro, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEvitar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIMCActionPerformed
        peso = Float.valueOf(txtPeso.getText());
        altura = Float.valueOf(txtAltura.getText());
        lblIMC.setText(String.valueOf(peso/(altura*altura)));
    }//GEN-LAST:event_btnCalcularIMCActionPerformed

    private void cboFundoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboFundoItemStateChanged
        verifica();
    }//GEN-LAST:event_cboFundoItemStateChanged

    private void btnPedirLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirLancheActionPerformed
        
        if(Float.valueOf(lblIMC.getText())>25.0 && rbtPodrao.isSelected()){
            
        lblDecisao.setText("Tem certeza?");
        lblGordoOuMagro.setIcon(new ImageIcon(getClass()
                        .getResource("/Criatividade/gordo.jpg")));
        }else if(Float.valueOf(lblIMC.getText())>25.0 && rbtSaudavel.isSelected()){
            
        lblDecisao.setText("OK! Comida saudável, vc está precisando.");
        lblGordoOuMagro.setIcon(new ImageIcon(getClass()
                        .getResource("/Criatividade/gordo.jpg")));
        }else if(Float.valueOf(lblIMC.getText())<25.0 && Float.valueOf(lblIMC.getText())>18.0 && rbtPodrao.isSelected()){
            
        lblDecisao.setText("Pode comer, mas tome cuidado.");
        lblGordoOuMagro.setIcon(new ImageIcon(getClass()
                        .getResource("/Criatividade/magro.jpg")));
        }else if(Float.valueOf(lblIMC.getText())<25.0 && Float.valueOf(lblIMC.getText())>18.0 && rbtSaudavel.isSelected()){
            
        lblDecisao.setText("Querendo ganhar massa?");
        lblGordoOuMagro.setIcon(new ImageIcon(getClass()
                        .getResource("/Criatividade/magro.jpg")));
        }else if(Float.valueOf(lblIMC.getText())<18.0 && rbtSaudavel.isSelected()){
            
        lblDecisao.setText("Tá maluco? Come um podrão, voce tá precisando magrelo.");
        lblGordoOuMagro.setIcon(new ImageIcon(getClass()
                        .getResource("/Criatividade/desnutrido.png")));
        }else{
            lblDecisao.setText("Que bom que tá comendo isso, ta muito magro já.");
        lblGordoOuMagro.setIcon(new ImageIcon(getClass()
                        .getResource("/Criatividade/desnutrido.png")));
        }
        
        
    }//GEN-LAST:event_btnPedirLancheActionPerformed

    private void rbtPodraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPodraoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtPodraoActionPerformed

    private void btnEvitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvitarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnEvitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Criatividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Criatividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Criatividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Criatividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Criatividade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFundo;
    private javax.swing.ButtonGroup btgComidas;
    private javax.swing.JButton btnCalcularIMC;
    private javax.swing.JButton btnEvitar;
    private javax.swing.JButton btnPedirLanche;
    private javax.swing.JComboBox<String> cboFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblDecisao;
    private javax.swing.JLabel lblGordoOuMagro;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblLanche;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblSituation;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtPodrao;
    private javax.swing.JRadioButton rbtSaudavel;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
